### ISSUE TITLE
RecyclerView的基本设计结构

### ISSUE THREAD

**Issue by chenchongyu** [SusionSuc/AdvancedAndroid#20]
RecyclerView的基本设计结构里的图都显示不出来啊

**Comment by chenchongyu** [comment]
> RecyclerView的基本设计结构里的图都显示不出来啊

忽略吧，网络问题

**Comment by Omooo** [comment]
阿西吧，我意思是我的库呢，打个广告：
https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/RecyclerView.md
逃）
